name: AWS Lambda Deployment

on: [push]

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
        session-name: switchbot-controller-deploy-session
        aws-region: ap-northeast-1
        
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Install dependencies and TypeScript
      run: |
        npm install
        npm install -g typescript

    - name: Build
      run: npm run build
    - name: Import Certificate Files
      run: |
        mkdir src/cert
        echo ${{ secrets.IOT_CERT }} >> src/cert/certificate.pem.crt
        echo ${{ secrets.IOT_PRIVATE_KEY }} >> src/cert/private.pem.key
        echo ${{ secrets.IOT_ROOT_CA }} >> src/cert/AmazonRootCA1.pem.key
    - name: Packaging
      run: |
        zip -dd lambda.zip node_modules dist/**/*.js package.json package-lock.json
    - name: Deploy to AWS Lambda
      run: |
        aws lambda update-function-code --function-name switchbot-controller --zip-file fileb://lambda.zip
