name: AWS Lambda Deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Install dependencies and TypeScript
      run: |
        npm install
        npm install -g typescript

    - name: Build
      run: npm run build
    - name: Import Certificate Files
      run: |
        mkdir src/cert
        echo ${{ secrets.IOT_CERT }} >> src/cert/certificate.pem.crt
        echo ${{ secrets.IOT_PRIVATE_KEY }} >> src/cert/private.pem.key
        echo ${{ secrets.IOT_ROOT_CA }} >> src/cert/AmazonRootCA1.pem.key
    - name: Packaging
      run: |
        zip -dd lambda.zip node_modules dist/**/*.js package.json package-lock.json
    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-lambda-deploy-function@v1
      with:
        function-name: MyFunctionName
        region: ap-northeast-1
        role: ${{ secrets.AWS_LAMBDA_ROLE_ARN }}
        runtime: nodejs18
        zip-file: lambda.zip
        secrets:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}